import ProjectDescription

let workspace = Workspace(
    name: "DemoTuist",
    projects: [
        "Apps/DemoApp",
        "Modules/FrameworkA",
        "Modules/FrameworkB"
    ],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
